project:
  type: website
  output-dir: docs

website:
  title: "AAI1001 - Personal Website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: fyp_project.qmd
        text: FYP Project
      - href: data_visualization.qmd
        text: Data Visualization
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



